fixtures:
  repositories:
    apt:             "git://github.com/puppetlabs/puppetlabs-apt"
    system:          "git://github.com/erwbgy/puppet-system"
    # transient dependencies of system
    augeasproviders: "git://github.com/hercules-team/augeasproviders"
    limits:          "git://github.com/erwbgy/puppet-limits"
    ntp:             "git://github.com/puppetlabs/puppetlabs-ntp"
    concat:          "git://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib: 
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.1.0"
  symlinks:
    pam_ssh_agent_auth: "#{source_dir}"
