fixtures:
  repositories:
    apt:             "git://github.com/puppetlabs/puppetlabs-apt"
    concat:          "git://github.com/puppetlabs/puppetlabs-concat.git"
    ssh:             "git://github.com/Seegras/puppet-ssh"
    stdlib: 
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.1.0"
  symlinks:
    pam_ssh_agent_auth: "#{source_dir}"
