fixtures:
  repositories:
    apt:   "git://github.com/puppetlabs/puppetlabs-apt"
    system: "git://github.com/erwbgy/puppet-system"
    stdlib: 
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib"
      ref: "4.1.0"
  symlinks:
    pam_ssh_agent_auth: "#{source_dir}"
