name 'cypherfox-pam_ssh_agent_auth'
version '0.1.0'

author 'Lutz Behnke <lutz.behnke@haw-hamburg.de>'
license 'Apache 2.0'
dependency 'erwbgy/system', '>= 0.7.4'
dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'puppetlabs/apt', '>= 1.4.1'
source 'git://github.com/haw-hh-ai-lab/puppet-pam_ssh_agent_auth'
project_page 'git://github.com/haw-hh-ai-lab/puppet-pam_ssh_agent_auth'
summary 'Authenticate user in PAM using a forwarded SSH agent'
description 'Authenticate user in PAM using a forwarded SSH agent'
